module Synthesizer.Modifiers.Ceiling
  where

import Synthesizer.Structure

-- | Apply some ceiling to the SoundEvent. This means that the samples generated by the SoundEvent cannot go higher than
-- the max.
ceiling :: Double -> SoundEvent -> SoundEvent
ceiling max event = event {samples = newSamples}
  where
    oldSamples = samples event
    newSamples samplingRate = map (`min` max) (oldSamples samplingRate)

-- | Apply some floor to the SoundEvent. This means that the samples generated by the SoundEvent cannot go lower than
-- the min.
floor :: Double -> SoundEvent -> SoundEvent
floor min event = event {samples = newSamples}
  where
    oldSamples = samples event
    newSamples samplingRate = map (`max` min) (oldSamples samplingRate)
